# This is the configuration file for the IdleBot plugin!
# More information and help can be found here: https://github.com/IdleBot-Development/IdleBot/wiki
# Comments refer to the option BELOW them

#    _____    _ _      ____        _
#   |_   _|  | | |    |  _ \      | |
#     | |  __| | | ___| |_) | ___ | |_
#     | | / _` | |/ _ \  _ < / _ \| __|
#    _| || (_| | |  __/ |_) | (_) | |_
#   |_____\__,_|_|\___|____/ \___/ \__|

# This is the token you get from your application in the Discord Developer Portal: https://discord.com/developers/applications | DO NOT INCLUDE THE <> | Ignored if discordSRV is true
botToken: <Bot Token Here>
# This is the ID of the Discord channel you want the bot to send messages to | DO NOT INCLUDE THE <> | Not needed if publicChannelMessagesEnabled is set to false
channelID: <Channel ID Here>
# Do you want this plugin to rely on DiscordSRV for account linking? (Recommended if you are using DiscordSRV)
discordSRV: false

# Category ignored if discordSRV is true
customBotActivity:
  # The type of activity in the bot's Discord status | default: watching | options: [watching, listening, playing, none]
  type: watching
  # The second part of the bot's Discord status. For example, if this says "idle players" the bot's status could be "Watching idle players" | default: idle players
  message: idle players

messageChannels:
  # Should players be allowed to have alerts sent to a public channel | default: true
  publicChannelMessagesEnabled: true
  # Should players be allowed to have alerts sent to a private channel | default: true
  privateChannelMessagesEnabled: true
  # The default message channel to set for players when they first link their account | default: public | options: [public, private]
  defaultMessageChannel: public

AFKMode:
  # Should players be allowed to go AFK just by standing still | default: true
  autoAFKEnabled: true
  # Should players be allowed to go AFK by typing a command | default: true
  manualAFKEnabled: true
    # Should players be allowed to have alerts repeated without becoming AFK again | default: false
  alertAutoTimeoutEnabled: false
  # The default mode for players to go AFK | default: auto | options: [auto, manual]
  defaultAFKMode: auto

idleTime:
  # (s) The default idle time for players who do not set their own | this must be between minimum and maximum idle time set below | default: 120
  defaultIdleTime: 120
  # (s) The minimum idle time a players can set for themselves | you can set this to a minimum of 5 seconds | default: 20
  minimumIdleTime: 20
  # (s) The maximum idle time a players can set for themselves | you can set this to a maximum of 86400 seconds (1 day) | default: 600
  maximumIdleTime: 600

alertRepeatTimeout:
  # (s) The default time between alerts for players who do not set their own | this must be between minimum and maximum alert repeat timeout set below | default: 20
  defaultAlertRepeatTimeout: 20
  # (s) The minimum time between alerts a players can set for themselves | you can set this to a minimum of 5 seconds | default: 10
  minimumAlertRepeatTimeout: 10
  # (s) The maximum time between alerts a players can set for themselves | you can set this to a maximum of 86400 seconds (1 day) | default: 120
  maximumAlertRepeatTimeout: 120