name: IdleBot
version: 1.3.0
main: io.github.idlebotdevelopment.idlebot.IdleBot
api-version: "1.14"
softdepend: [DiscordSRV]
commands:
  idlebot:
    description: The main command to control and use this plugin
    usage: /idlebot <advancement | afkmode | afktime | alerttimeout | alert | channel | cleardata | link | location | afk | unlink | info | xplevel> [additional command arguments]
    aliases: ib
