name: IdleBot
version: 0.1.1
main: io.github.camshaft54.idlebot.IdleBot
api-version: "1.16"
commands:
  idlebot:
    description: The main command to control and use this plugin
    usage: /<command> <subcommand>
    aliases: ib
